export const DashboardStyleSheet = {
  dashboardContainer: {
    margin: "0.3rem",
    padding: "1rem",
  },
  dashboardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dashboardTitle: {
    fontSize: "25px",
    fontWeight: "bold",
    margin: 0,
  },
  createButton: {
    height: "2.5rem",
    width: "9rem",
    borderRadius: "0.7rem",
    backgroundColor: "#292965",
    color: "white",
    fontWeight: 600,
    border: "none",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
    cursor: "pointer",
  },
  dashboardFilters: {
    margin: "5px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "1rem",
    borderRadius: "1rem",
    boxShadow: "0 4px 8px rgba(73, 20, 141, 0.5)",
    gap: "1rem",
    flexWrap: "wrap",
  },
  dashboardSearch: {
    flex: 1,
  },
  dashboardCategory: {
    flex: 1,
  },
  dashboardStatus: {
    flex: 1,
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: "8px",
    border: "1px solid #ccc",
    fontSize: "15px",
    transition: "all 0.3s ease",
  },
  select: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: "8px",
    border: "1px solid #ccc",
    fontSize: "15px",
    backgroundImage:
      "url(\"data:image/svg+xml;utf8,<svg fill='black' height='14' viewBox='0 0 24 24' width='14' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/></svg>\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 5px center",
    backgroundSize: "24px",
    appearance: "none",
  },
  dashboardSubmit: {
    display: "flex",
    flex: 1,
    justifyContent: "center",
    padding: "1.5%",
    borderRadius: "18px",
    backgroundColor: "#292965",
    border: "none",
    maxWidth: "12rem",
    cursor: "pointer",
  },
  searchBtn: {
    backgroundColor: "#292965",
    color: "white",
    border: "none",
    fontWeight: 700,
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
  },
  dashboardMainTable: {
    display: "flex",
    flexDirection: "column",
    margin: "1rem",
    padding: "1rem",
    borderRadius: "22px",
    boxShadow: "0 4px 8px rgba(73, 20, 141, 0.5)",
  },
  summary: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
  },
  summaryName: {
    flex: 1,
    fontSize: "2vw",
    fontWeight: 700,
  },
  show: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  showSelector: {
    height: "2.2rem",
    borderRadius: "6px",
    appearance: "none",
    backgroundColor: "#f0f0f0",
    border: "1px solid #ccc",
    padding: "0 10px",
    width: "120px",
    color: "#333",
    backgroundImage:
      "url(\"data:image/svg+xml;utf8,<svg fill='black' height='14' viewBox='0 0 24 24' width='14' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/></svg>\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 5px center",
    backgroundSize: "18px",
  },
  showLabel: {
    fontSize: "13px",
    color: "grey",
    fontWeight: 600,
  },
  dispatch: {
    height: "2.2rem",
    padding: "0 1rem",
    borderRadius: "7px",
    border: "none",
    backgroundColor: "#292965",
    color: "white",
    fontSize: "13px",
    fontWeight: 600,
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
  },
  tableContent: {
    overflowX: "auto",
  },
  mainTable: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    backgroundColor: "#f5f5f5",
    fontWeight: 600,
    textAlign: "left",
    padding: "12px 15px",
    borderBottom: "1px solid #ddd",
    fontSize: "14px",
  },
  td: {
    textAlign: "left",
    padding: "12px 15px",
    borderBottom: "1px solid #ddd",
    fontSize: "14px",
  },
  trHover: {
    backgroundColor: "#f9f9f9",
  },
  checkboxId: {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
  },
  pagination: {
    marginLeft: "0.5rem",
    display: "flex",
    gap: "5px",
    justifyContent: "center",
    flexWrap: "wrap",
    alignItems: "center",
  },
  page: {
    minWidth: "40px",
    textAlign: "center",
    padding: "8px 12px",
    borderRadius: "6px",
    backgroundColor: "#f2f2f2",
    transition: "0.2s ease",
    boxSizing: "border-box",
  },
  pageActive: {
    backgroundColor: "#292965",
    color: "white",
    fontWeight: "bold",
  },
  arrow: {
    minWidth: "40px",
    textAlign: "center",
    padding: "8px 12px",
    borderRadius: "6px",
    transition: "0.2s ease",
  },
  arrowDisabled: {
    pointerEvents: "none",
    opacity: 0.4,
  },
};

